# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13fTCu_zZrjrv64GEOo7OS0vtr9AO1m2v
"""

#!pip install pgmpy

#!pip install pomegranate

#!pip install bnlearn

#!pip install ortools

import random
import multiprocessing
import pickle
import os
import time
import pgmpy.models
import csv
import sklearn.model_selection
import pandas as pd

import lptree
import dataset
import cpnet
import mdllearn
import bayesian_network
import renault
import experiment

import ensemble
import aaailearn

def read_csv_train_test(file):
     with open(file, mode='r') as f:
        reader = csv.DictReader(f)
        d = []
        for row in reader:
            d.append(row)
        train, test = sklearn.model_selection.train_test_split(d, test_size=0.2, random_state=42)
        return pd.DataFrame(train), pd.DataFrame(test)



def run_find(ds_name):
    df = pd.read_csv("datasets/renault_"+ds_name+".csv")

    # Bayesian network
    print("Bayesian network")
    if os.path.isfile("models/"+ds_name+"-bn.bif"):
        bn = bayesian_network.BN.load("models/"+ds_name+"-bn.bif", df)
    else:
        experiment.run_expe_recom(ds_name)
    


    print("CP-net (BN+HC)")
    if os.path.isfile("models/cpnet-"+ds_name+"-bn+hc.pickle"):
        net = pickle.load(open("models/cpnet-"+ds_name+"-bn+hc.pickle","rb"))
    else:
        experiment.run_expe_recom(ds_name)

    assign_value= renault.variable_choisi('small')
    assign_value = {k: str(v) for k, v in assign_value.items()}
    find(list(df.columns),assign_value,net)
    # net.export("models/cpnet-"+ds_name+"-bn+hc.dot")


def find(var_order, assign_value, model):
      random.shuffle(var_order)
      predict= assign_value.copy()
      for v in var_order:
            if v not in assign_value:
                value = model.predict_one_variable(predict, v)
                assign_value[v] = value
      print(assign_value)


def main():
    print("DATASET: SMALL")

    run_find("small")